[package]
name = "comparer_rust"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
rusqlite = { version = "0.31", features = ["bundled"] }
rayon = "1.8"
clap = { version = "4.4", features = ["derive", "env"] }
